# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

# CINTENT >> MANUAL TRIGGER
# on:
#   pull_request:
#   schedule:
#     - cron: "0 2 * * 6"
#   workflow_dispatch:
on: [repository_dispatch, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        # CINTENT >> CHANGE_VERSION
        # python-version: [ 3.8 ]
        python-version: [ "3.10" ]

        # CINTENT >> UNSUPPORTED_OS
        # os: [ ubuntu-latest, macOS-latest, windows-latest ]
        os: [ ubuntu-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@a606c80c34ec190c6a20dea33d6d58ddb6c4e0cc

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.py

      - name: Install
        run: pip install pytest -e . --only-binary=numpy,scipy,matplotlib,torch
        env:
          PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu

      - name: Test with pytest
        run: python -m pytest -v

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@a606c80c34ec190c6a20dea33d6d58ddb6c4e0cc

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: setup.py

      - name: Lint with flake8
        run: |
          python -m pip install flake8
          python -m flake8 .

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}